MinisterePortailWeb/Models/ErrorViewModel.cs
namespace MinisterePortailWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MinisterePortailWeb/Controllers/E-ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ministere_Portail_Web.Controllers
{
    public class E_ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MinisterePortailWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MinisterePortailWeb.Models;
using System.Diagnostics;

namespace MinisterePortailWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MinisterePortailWeb/Controllers/MissionController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ministere_Portail_Web.Controllers
{
    public class MissionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MinisterePortailWeb/Views/E_Services/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="text-center">
    
    <h1 class="display-4">E-Services</h1>
    <div class="container row">
        <div class="list-group col-6" >
            <a data-id="particulier" href="#particulier" class="list-group-item">Particulier</a>
            <a data-id="pro" href="#pro" class="list-group-item">Professionnel</a>
            <a data-id="mobiles" href="#mobiles" class="list-group-item">Service mobile</a>
        </div>
        <div class="content-area col-6">
            <div id="particulier" class="list-group">
                <a href="http://reclamation.mtpnet.gov.ma/index.php5?page=citoyen.AccueilCitoyen" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-flag"></i>  Reclamation en ligne</a>
            </div>
            <div id="mobiles" class="list-group">
                <a href="http://maroute.mtpnet.gov.ma/html/#/app/home" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-road"></i> Ma route</a>
                <a href="http://onelink.to/maplage" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-sharp fa-solid fa-umbrella-beach"></i> Ma plage</a>
            </div>
            <div id="pro" class="list-group">
                <a href="http://www.equipement.gov.ma/Espace-Fournisseurs/" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-cart-shopping"></i> Espace achat</a>
                <a href="http://www.equipement.gov.ma/Ingenierie/Systemes-regissant-la-Profession/Pages/Qualification-et-classification-des-Entreprises-BTP.aspx" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-building"></i>  Qualification et classification des entreprises de BTP</a>
                <a href="https://ajal.finances.gov.ma/" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-calendar"></i>  Ajal</a>
                <a href="http://www.equipement.gov.ma/Ingenierie/Pages/Revision-des-prix-baremes-indexation.aspx" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-money-bill"></i>  Révision des prix – barèmes d’indexation</a>
                <a href="http://www.equipement.gov.ma/Ingenierie/Systemes-regissant-la-Profession/Pages/Qualification-et-Classification-des-Laboratoires-de-BTP.aspx" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-flask-vial"></i>  Qualification et classification des laboratoires de BTP</a>
                <a href="http://www.equipement.gov.ma/Ingenierie/Systemes-regissant-la-Profession/Pages/Agrement-des-Bureaux-d-Etudes.aspx" target="_blank" rel="noreferrer noopener" class="list-group-item"><i class="fa-solid fa-computer"></i>  Agréments des bureaux d’étude</a>

            </div>
        </div>

    </div>

</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('div.content-area div').hide();
            $('a').on("click", function () {
                $('a').removeClass("active")
                $(this).addClass('active')

                $('div.content-area div').hide(); // Hide all divs in the content-area
                $('div#' + $(this).attr('data-id')).show(); // Show the corresponding div
            })
        })
    </script>
    <script type="text/javascript">
        document.getElementById("services").classList.add('active');
        document.getElementById("home").classList.remove('active');
        document.getElementById("mission").classList.remove('active');
    </script>
}

MinisterePortailWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <br />
    <img src="/logoMinistere.png" class="img-fluid" alt="Responsive image" />
    <br />
    <h1 class="display-4">Bienvenue</h1>
    <p>Votre portail au Ministère de l’Equipement et de l’Eau.</p>

</div>

MinisterePortailWeb/Views/Mission/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <br />
    <h2>Ministère de l’Equipement et de l’Eau</h2>
    <p>
        Le Ministère de l’Équipement et de l’Eau prend en charge des secteurs vitaux qui jouent un rôle essentiel dans le développement économique et social du pays, participe directement ou indirectement à l’aménagement du territoire, à la réduction des disparités régionales et à la création d’un environnement propice pour l’investissement.

        Sa mission consiste à élaborer, mettre en œuvre et coordonner la politique du Gouvernement relative au secteur des infrastructures routières, portuaires, hydrauliques et de la météorologie.
    </p>
    <h3>Structure organisationnelle :</h3>
    <p>
        Le Ministère de l'Equipement et de l'Eau comprend, en outre du cabinet du Ministre, l’administration centrale et les services déconcentrés.

        L’administration centrale comprend :
    </p>
    <div class="container row">
        <div class="side-bar col-6">
            <ul class="list-group list-unstyled px-2">
                <li  class="list-group-item"><a  class="text-decoration-none">Le Secrétariat Général</a></li>
                <li class="list-group-item"><a  class="text-decoration-none">Le Conseil Général de l’Equipement et de l’Eau</a></li>
                <li class="list-group-item"><a  class="text-decoration-none">L'Inspection Générale</a></li>
                <li data-id="strategie" class="list-group-item"><a href="#strategie" class="text-decoration-none">La Direction Générale de la Stratégie, des Ressources et du Numérique qui comprend :</a></li>
                <li data-id="route" class="list-group-item"><a href="#route" class="text-decoration-none">La Direction Générale des Routes qui comprend :</a></li>
                <li data-id="Hydraulique" class="list-group-item"><a href="#Hydraulique" class="text-decoration-none">La Direction Générale de l’Hydraulique qui comprend :</a></li>
                <li data-id="meteorologie" class="list-group-item"><a href="#meteorologie" class="text-decoration-none">La Direction Générale de la Météorologie qui comprend :</a></li>
                <li class="list-group-item"><a class="text-decoration-none">La Direction des Ports et du Domaine Public Maritime</a></li>
            </ul>
        </div>
        <div class="content-area col-6">
            <div id="strategie" class="list-group">
                    <p class="list-group-item">La Direction de la Stratégie et du Financement</p>
                    <p class="list-group-item">La Direction des Ressources Humaines</p>
                    <p class="list-group-item">La Direction des Affaires Administratives et Juridiques</p>
                    <p class="list-group-item">La Direction des Systèmes d'Information et du Numérique</>
                    <p class="list-group-item">La Direction des Affaires Techniques et des Relations avec la Profession</p>
            </div>
            <div id="route" class="list-group">
                <p class="list-group-item">La Direction des Etudes, du Développement et de la Recherche Routière</p>
                <p class="list-group-item">La Direction des Travaux et de l'Exploitation Routière</p>
            </div>
            <div id="Hydraulique" class="list-group">
                <p class="list-group-item">La Direction de la Recherche et de la Planification de l'Eau</p>
                <p class="list-group-item">La Direction des Aménagements Hydrauliques</p>
            </div>
            <div id="meteorologie" class="list-group">
                <p class="list-group-item">La Direction des Prévisions et des Recherches Météorologiques</p>
                <p class="list-group-item">La Direction des Systèmes d’Observation.</p>
            </div>
        </div>
    </div>
    
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $('div.content-area div').hide();
            $('li').on("click", function () {
                $('li').removeClass("active")
                $(this).addClass('active')

                $('div.content-area div').hide(); // Hide all divs in the content-area
                $('div#' + $(this).attr('data-id')).show(); // Show the corresponding div
            })
        })
    </script>
    <script type="text/javascript">
        document.getElementById("mission").classList.add('active');
        document.getElementById("home").classList.remove('active');
        document.getElementById("services").classList.remove('active');

    </script>
}

MinisterePortailWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MinisterePortailWeb</title>
    <link rel="stylesheet" href="~/css/lux.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="/logoMinistere.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light py-0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="img-fluid" src="./royaumedumaroc.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a id="home" class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="mission" class="nav-link " asp-area="" asp-controller="Mission" asp-action="Index">Mission</a>
                       </li>
                        <li class="nav-item">
                            <a id="services" class="nav-link " asp-area="" asp-controller="E_Services" asp-action="Index">E-Services</a>
                        </li>
                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MinisterePortailWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>